### ISSUE TITLE
Add Search feature

### ISSUE THREAD

**Issue by Pabl0cks** [scaffold-eth/se-2-docs#6]
When we have initial version of Docs in production, could be interesting to add a search bar.

Docusaurus docs offer a few options for that:
- 🥇 [Algolia DocSearch](https://docusaurus.io/docs/search#using-algolia-docsearch) (official)
- 👥 [Typesense DocSearch](https://docusaurus.io/docs/search#using-typesense-docsearch)
- 👥 [Local Search](https://docusaurus.io/docs/search#using-local-search)
- 👥 [Your own SearchBar component](https://docusaurus.io/docs/search#using-your-own-search)

Algolia DocSearch is free for open-source projects, just have to [apply to the DocSearch program](https://docsearch.algolia.com/apply). I guess we shouldn't have problems getting accepted.

A few examples of other projects:
- [Uniswap Docs](https://docs.uniswap.org/) is using Algolia DocSearch
- [Solana](https://docs.solana.com/) uses Algolia too.
- [Chia Docs](https://docs.chia.net/) is using a local search =>  `@easyops-cn/docusaurus-search-local',` Found another website using the same local search plugin => [Courier](https://www.courier.com/docs/)
- [Celo](https://docs.celo.org/) uses Algolia DocSearch but removed Search by Algolia logo
- [Flow](https://developers.flow.com/concepts/intro) was using algolia and removed it 12 hours ago 🧐   

Update: Just realized [ethereum.org docs](https://ethereum.org/en/developers/docs/) is also using DocSearch but without Algolia reference.

**Comment by carletex** [comment]
> Question :
Do we need a search feature in the current situation? Like I see currently the docs are pretty intuitive and easily navigable / short. But we will be needing to make decisions in future (we can wait for Carlos if the docs remains short until he comes for the decesion 🙌 )

I agree with this. It's not a huge doc site (at least for now), so the search feature is not critical. Maybe we could defer this a bit... unless someone really likes the idea and wants to implement it :D

**Comment by FilipHarald** [comment]
I checked out the local-search alternatives. I only got one to work, it's rudimentary but gets the job done. This indexes the pages during build, but after that no additional services needs to be hosted. I made a working example here: https://github.com/FilipHarald/se-2-docs/tree/feat/serch_bar

**Comment by Pabl0cks** [comment]
Closing, merged in https://github.com/scaffold-eth/se-2-docs/pull/78
