### ISSUE TITLE
Add the useTransactor hook

### ISSUE THREAD

**Issue by carletex** [scaffold-eth/se-2-docs#68]
If I want to want to send a simple transaction (like sending ETH), using `useTransactor` is nice because it gives you UI feedback.

```tsx
  const writeTx = useTransactor();

  <button
    className="btn btn-primary"
    onClick={() => {
      writeTx({
        to: "0xAddress",
        value: parseEther("0.001"),
      });
    }}
  >
    Send transaction
  </button>
```

Should we place it under the "Interacting with Your Smart Contracts" section?

**Comment by FilipHarald** [comment]
I'm giving this a try. Starting with a similar approach to the others under "Interacting with Your Smart Contracts". I think it's a good place to have it :)

**Comment by FilipHarald** [comment]
#76
