### ISSUE TITLE
Add foundry installation steps

### ISSUE THREAD

**Issue by danitome24** [scaffold-eth/se-2-docs#85]
### Feature Request

When starting a new project, at page `QuickStart > Installation` there's no info about how to start a project with Foundry. 

I propose to build some docs with Tabs system, where you can see two Tabs (one for hardhat and one for Foundry) and see Installation details for each. The same way that is done in `QuickStart > Environment`.

**Comment by technophile-04** [comment]
Checkout https://github.com/scaffold-eth/se-2-docs/pull/86#issuecomment-2493515231
